import Head from "next/head";
import { FunctionComponent } from "react";

const Home: FunctionComponent = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <h1>Home Page</h1>
    </div>
  );
};

export default Home;
